// Generated by ops/check_gate_trust.py from data/whitelist.txt; do not edit by hand.
export const GATE_TRUST = {"verified_bot": true, "ua_allowlist_enabled": false, "ip_cidrs": [["97.64.18.11", 32], ["176.122.161.108", 32]]} as const;
export const GATE_TRUST_IPS: Set<string> = new Set(["97.64.18.11", "176.122.161.108"]);
export const GATE_TRUST_NETWORKS: [string, number][] = [["97.64.18.11", 32], ["176.122.161.108", 32]];
