/**
 * Limooo - serverless personal website and admin system
 *
 * Copyright (C) 2026 Limooo <https://limooo.cn/>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// Generated by ops/check_gate_trust.py from data/whitelist.txt; do not edit by hand.
export const GATE_TRUST = {"verified_bot": true, "ua_allowlist_enabled": false, "ip_cidrs": [["97.64.18.11", 32], ["176.122.161.108", 32]]} as const;
export const GATE_TRUST_IPS: Set<string> = new Set(["97.64.18.11", "176.122.161.108"]);
export const GATE_TRUST_NETWORKS: [string, number][] = [["97.64.18.11", 32], ["176.122.161.108", 32]];
