#!/usr/bin/env python3

# Limooo - serverless personal website and admin system
#
# Copyright (C) 2026 Limooo <https://limooo.cn/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""从 data/whitelist.txt 与 config-contract.json 生成门禁信任配置（docs/14）。

输出：
  - 校验白名单格式（ASN 与 IP-CIDR 两段都校验）；
  - `--emit` 时生成 functions/_data/gateTrust.ts：只含运行时真正消费的
    verified_bot / ip_cidrs（ASN 是 WAF 的输入，不进 isolate，见 W4-4）；
  - ASN 计数仍出现在 stdout 的 --json 摘要里，供审计与 readme 核对；
  - 不读取任何密钥。
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACT_PATH = ROOT / "config-contract.json"
WHITELIST_PATH = ROOT / "data" / "whitelist.txt"
OUTPUT_PATH = ROOT / "functions" / "_data" / "gateTrust.ts"

ASN_RE = re.compile(r"^ASN/(\d{1,10})$", re.I)
IP_CIDR_RE = re.compile(
    r"^IP-CIDR/([0-9A-Fa-f:.]+)/(\d{1,3})$",
    re.I,
)

# 生成物顶部的 AGPL 头（docs/22 W8-7）。措辞与 src/config.py 等手写文件里的
# 头逐字一致，只把注释符号换成 TS 的块注释；src/build.py 生成
# functions/_lib/config.ts 与 functions/_data/*.ts 时有一份同文副本，
# 改这里请一并改那边。
LICENSE_HEADER_TS = """\
/**
 * Limooo - serverless personal website and admin system
 *
 * Copyright (C) 2026 Limooo <https://limooo.cn/>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
"""


def load_whitelist(path: Path) -> tuple[list[int], list[tuple[str, int]]]:
    asns: list[int] = []
    networks: list[tuple[str, int]] = []
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError as exc:
        raise RuntimeError(f"cannot read whitelist {path}: {exc}") from exc

    for raw in lines:
        line = re.sub(r"#.*$", "", raw).strip()
        if not line:
            continue
        asn = ASN_RE.match(line)
        if asn:
            asns.append(int(asn.group(1)))
            continue
        cidr = IP_CIDR_RE.match(line)
        if cidr:
            prefix = int(cidr.group(2))
            if prefix < 0 or prefix > 128:
                raise RuntimeError(f"invalid CIDR prefix: {line}")
            networks.append((cidr.group(1), prefix))
            continue
        raise RuntimeError(f"cannot parse whitelist line: {line}")

    return sorted(set(asns)), networks


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--emit", action="store_true", help="write gateTrust.ts")
    args = parser.parse_args()

    contract = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    gate_trust = contract.get("gate_trust", {})
    # ASN 仍要解析、仍要校验格式：WAF 的 js_challenge 规则从 data/whitelist.txt
    # 的 ASN 段生成。但运行时（functions/_middleware.ts）只读 verified_bot /
    # ip_cidrs，所以下面的 runtime payload 不带 low_risk_asns —— 320 条 ASN
    # 打进 isolate 只是死数据，真实消费方是 WAF（W4-4）。
    asns, networks = load_whitelist(WHITELIST_PATH)

    payload = {
        "verified_bot": gate_trust.get("verified_bot", True),
        "ua_allowlist_enabled": gate_trust.get("ua_allowlist_enabled", False),
        "ip_cidrs": networks,
    }

    if args.emit:
        OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        ts = (
            LICENSE_HEADER_TS
            + "\n// Generated by ops/check_gate_trust.py from data/whitelist.txt; do not edit by hand.\n"
            f"export const GATE_TRUST = {json.dumps(payload, ensure_ascii=False)} as const;\n"
            f"export const GATE_TRUST_IPS: Set<string> = new Set({json.dumps([ip for ip, _ in networks])});\n"
            f"export const GATE_TRUST_NETWORKS: [string, number][] = {json.dumps(networks)};\n"
        )
        OUTPUT_PATH.write_text(ts, encoding="utf-8")

    print(
        json.dumps(
            {
                "ok": True,
                "verified_bot": payload["verified_bot"],
                "ua_allowlist_enabled": payload["ua_allowlist_enabled"],
                "asns": len(asns),
                "ip_cidrs": len(networks),
                "emitted": str(OUTPUT_PATH) if args.emit else None,
            },
            ensure_ascii=False,
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
